### PR TITLE
chore: repo cleanup

### PR DESCRIPTION
**Pull request by R1kaB3rN**
- Updates the permissions for some files and organizes them.
- Adds a Makefile to install the `protonfixes` module and build `xrandr`, which is expected to be built within the Steam Runtime.

Setting up the Steam Runtime environment must be done through a container management framework such as podman or docker. Example through distrobox within the project directory:

1. `distrobox create -n sniper --image registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta`
2. `distrobox enter sniper`
3. `git submodule update --init --recursive`
4. `make`
5. `make install`

Edit:

As a result, the distributable `./dist/protonfixes` will be created and which will contain the following files:

```
cabextract  download.py       gamefixes-battlenet  gamefixes-humble   gamefixes-umu           libmspack.so.0      util.py
checks.py   engine.py         gamefixes-ea         gamefixes-itchio   gamefixes-zoomplatform  libmspack.so.0.1.0  verbs
config.py   fix.py            gamefixes-egs        gamefixes-steam    __init__.py             logger.py           winetricks
debug.py    gamefixes-amazon  gamefixes-gog        gamefixes-ubisoft  libmspack.so            steamhelper.py      xrandr
```

where only `cabextract`, `libmspack.so`, `xrandr` and `winetricks` will be writable and executable.

TODO:
- [x] Build cabextract and libmspack.so.0
- [x] Update Makefile in proton-ge-custom
- [x] Add Github Action for build

### CODE REVIEW

**Comment by R1kaB3rN** [comment]
@loathingkernel review on the Makefile would be appreciated.

**Comment by loathingKernel** [comment]
the Makefile LGTM so far, I'll keep an eye out to look into it again once the PR is ready.

**Comment by R1kaB3rN** [comment]
cc @loathingKernel 

A second review would be appreciated.

**Comment by R1kaB3rN** [comment]
Tested locally by overwriting the relevant binaries and protonfixes directory in GE-Proton9-11 then running the winetricks verbs quartz, wmp11 and cabextract using umu-launcher.

Log: https://gist.github.com/R1kaB3rN/ca8d61973f4cc6fde953b44bdc24c875

Should be ready to merge.

**Pull request merged**
