### PR TITLE
Mod support for multiple Bethesda games

### LINKED ISSUE #103: Fallout 4 fix breaks Mod Organizer 2
The fix, gamefixes-steam/377160.py overrides what exe is ran, MO2 hooks into the default launched exe to run itself.

**To Reproduce**
Install MO2 (Easiest is via https://github.com/rockerbacon/modorganizer2-linux-installer )

Install F4SE (https://www.nexusmods.com/fallout4/mods/42147 extract files into game folder [no subfolder])

Launch Fallout 4
**Expected behavior**
Launching fallout 4 should bring up MO2 ran via the default launcher, it should *not* be bypassed 

**Logs**
n/a

**Operating System:**
 - Distro and Version: KDE Neon 6.0
 - Proton Version: GE9-11

**Game (if applicable):**
 - Game Name: fallout 4
 - Game ID: 377160

**Additional Information**
https://github.com/rockerbacon/modorganizer2-linux-installer/issues/598

### PR DESCRIPTION
**Pull request by Root-Core**
- Fallout 3 - Game of the Year Edition
- Fallout 4
- Fallout: New Vegas
- The Elder Scrolls IV: Oblivion
- The Elder Scrolls V: Skyrim
- The Elder Scrolls V: Skyrim Special Edition
- Starfield

This adds support for modorganizer2 and manually installed script runners.

Closes #103

### CODE REVIEW

**Comment by Root-Core** [comment]
CC @gunqqer, could you test if that works for you?

**Comment by gunqqer** [comment]
> CC @gunqqer, could you test if that works for you?

I tested only Fallout 4 with mo2 and it properly launched using the patched exe (I haven't tested any other functionality)

**Comment by Root-Core** [comment]
@R1kaB3rN We could also create generic mod support in a separate module, perhaps using `engine.py` to detect the engine for some games. There are already some fixes that implement mod support. By having them in one place, we can easily have a toggle in config or env to enable/disable support or override the replaced string for a game.

**Comment by GloriousEggroll** [comment]
@Root-Core are you in our OWC discord? This looks good to me

**Comment by Root-Core** [comment]
@GloriousEggroll Do you mean the Nobara/Proton-GE discord? Yes, I'm generally not that active on discord servers though, but I'm online/reachable. My nickname is aede / username root_core.

**Comment by GloriousEggroll** [comment]
> @GloriousEggroll Do you mean the Nobara/Proton-GE discord? Yes, I'm generally not that active on discord servers though, but I'm online/reachable. My nickname is aede / username root_core.

nono, we have a separate discord for OWC memebers/stuff, I'd like to send you an invite if you could ping me in the Nobara discord I'll send the invite

**Comment by Root-Core** [comment]
@GloriousEggroll I can't send you DMs, but I added you as a friend.

**Comment by Root-Core** [comment]
@GloriousEggroll My nickname is `aede` / username `root_core`.

**Pull request merged**
