### PR TITLE
Many Video Playback fixes for Yuzusoft VN's

### PR DESCRIPTION
**Pull request by CreeperofDoom**
Allows WMP9 Video Playback to work for many Yuzusoft Steam titles

### CODE REVIEW

**Comment by marianoag** [comment]
You should try to check what's really necessary:

both wmp9_x86_64 and wmp9? I don't even think that both wmp9 and klite are needed, in ProtonDB i saw wmp9 or wmp11, just choose one.

Then if quartz is not enough (maybe amstream also) but both of those are called by directshow in winetricks, so if you use directshow they are redundant.

**Comment by CreeperofDoom** [comment]
> You should try to check what's really necessary:
> 
> both wmp9_x86_64 and wmp9? I don't even think that both wmp9 and klite are needed, in ProtonDB i saw wmp9 or wmp11, just choose one.
> 
> Then if quartz is not enough (maybe amstream also) but both of those are called by directshow in winetricks, so if you use directshow they are redundant.

I wanted to ensure it would work, i tried the necessary commands to make sure it would work. Quartz fixes the audio problem with the video playback and maybe the Proton Audio Converter script helped.

**Comment by marianoag** [comment]
> I wanted to ensure it would work, i tried the necessary commands to make sure it would work. Quartz fixes the audio problem with the video playback and maybe the Proton Audio Converter script helped.

Sure it will work but it is overkill. To make it clean you should delete the prefix and try again, since it's impossible to uninstall a winetricks verb.

If i were you i would try quartz and wmp9, if it doesn't work try directshow and if it works remove quartz.

If not delete the prefix again and try quartz and klite, and the directshow as above if it didn't work.

**Comment by CreeperofDoom** [comment]
> > I wanted to ensure it would work, i tried the necessary commands to make sure it would work. Quartz fixes the audio problem with the video playback and maybe the Proton Audio Converter script helped.
> 
> Sure it will work but it is overkill. To make it clean you should delete the prefix and try again, since it's impossible to uninstall a winetricks verb.
> 
> If i were you i would try quartz and wmp9, if it doesn't work try directshow and if it works remove quartz.
> 
> If not delete the prefix again and try quartz and klite, and the directshow as above if it didn't work.

Trying Directshow, Quartz and Klite result in the same nothing as before. Trying Quartz and Klite result in a plain black screen, trying wmp9 itself brings an error, trying wmp9_x86_64 brings and error. If i try all the above (which is the one i tried to publish) it will work normal

**Comment by marianoag** [comment]
> Trying Directshow, Quartz and Klite result in the same nothing as before. Trying Quartz and Klite result in a plain black screen, trying wmp9 itself brings an error, trying wmp9_x86_64 brings and error. If i try all the above (which is the one i tried to publish) it will work normal. changing the order does nothing. I made sure to clear the Prefix before trying each new one. and trying quartz, wmp9 and wmp9_x86_x64 results in video but broken audio

That's odd that you need two wmp9. Also odd that i didn't see that in ProtonDB but also  it's  common to see reports saying that everything works fine but the cutscenes are not displayed or there's no audio.

If you haven't tried or you don't remember i bet that just directshow + wmp9 and possibly disable protonaudioconverter for the missing audio could work.

**Comment by CreeperofDoom** [comment]
> > > I wanted to ensure it would work, i tried the necessary commands to make sure it would work. Quartz fixes the audio problem with the video playback and maybe the Proton Audio Converter script helped.
> > 
> > 
> > Sure it will work but it is overkill. To make it clean you should delete the prefix and try again, since it's impossible to uninstall a winetricks verb.
> > If i were you i would try quartz and wmp9, if it doesn't work try directshow and if it works remove quartz.
> > If not delete the prefix again and try quartz and klite, and the directshow as above if it didn't work.
> 
> Trying Directshow, Quartz and Klite result in the same nothing as before. Trying Quartz and Klite result in a plain black screen, trying wmp9 itself brings an error, trying wmp9_x86_64 brings and error. If i try all the above (which is the one i tried to publish) it will work normal. changing the order does nothing. I made sure to clear the Prefix before trying each new one. and trying quartz, wmp9 and wmp9_x86_x64 results in video but broken audio

Alright i got it. Quartz, WMP9 and Directshow + DisableProtonAudioconverter (if its not there the audio doesn’t play) If i try it with Directshow and without WMP9 it doesn’t work, if i try it without quartz and with directshow it doesn’t work. Please, trying all this out was stressful enough and i just want 

> > Trying Directshow, Quartz and Klite result in the same nothing as before. Trying Quartz and Klite result in a plain black screen, trying wmp9 itself brings an error, trying wmp9_x86_64 brings and error. If i try all the above (which is the one i tried to publish) it will work normal. changing the order does nothing. I made sure to clear the Prefix before trying each new one. and trying quartz, wmp9 and wmp9_x86_x64 results in video but broken audio
> 
> That's odd that you need two wmp9. Also odd that i didn't see that in ProtonDB but also it's common to see reports saying that everything works fine but the cutscenes are not displayed or there's no audio.
> 
> If you haven't tried or you don't remember i bet that just directshow + wmp9 and possibly disable protonaudioconverter for the missing audio could work.

Alright i got it. Quartz, WMP9 and Directshow + DisableProtonAudioconverter (if its not there the audio doesn’t play) If i try it with Directshow and without WMP9 it doesn’t work, if i try it without quartz and with directshow it doesn’t work. Please, trying all this out was stressful enough

**Pull request closed without merging**
