### PR TITLE
Update fixes for YUZUSOFT titles

### PR DESCRIPTION
**Pull request by R1kaB3rN**
Related to https://github.com/Open-Wine-Components/umu-protonfixes/issues/111

### CODE REVIEW

**Comment by R1kaB3rN** [comment]
CC @layercak3.

A review would be appreciated.

**Comment by CreeperofDoom** [comment]
The new fix works fine, but...

I tested the title Riddle Joker:
One user reported there is a Pixelation issue with the WMP Video Files which i dont know how to fix, applying the vomstyle launch command breaks Video Playback.

The old one with the WMP stuff worked perfect it seemed. But Upgrading GE-Proton would break it, requiring the Proton Data to be cleared to remedy it.

Performance Issues are caused by a broken Pre-Compiled Shader Cache. Deleting that and booting Riddle Joker offline fixes the problem (going online on Steam will force a redownload of the broken cache, Coming at 5 Gigabytes)

**Comment by R1kaB3rN** [comment]
If it works, that's fine. Compared to the old fix, this new one would be preferred as it avoids having new users from manually clearing Proton-related data for future wine prefix upgrades. The `wmp11` verb will need to be thoroughly investigated and resolved separately at another time. 

We run winetricks verbs to fix games, and should be perceived as temporary workarounds until there's a solution upstream. Therefore, if a decent native solution (e.g., gstreamer bad plugins, winegstreamer) exists, it should always be preferred over dubious binaries sourced from winetricks verbs. 

As for potential regressions from wine that may effect playback, that's something everyone who uses GE-Proton should be prepared for and what's certain is that video playback will be broken after the wine prefix upgrade. If there happens to be a regression in winegstreamer, as always, the problem should be reported upstream and we can always reintroduce the old fix in the future when necessary.

**Comment by CreeperofDoom** [comment]
IMG_5658
I get this when attempting to play one of the Video Files in Riddle Joker. GE-Proton 9-13 used

**Comment by CreeperofDoom** [comment]
Actually no Upgrading isn’t the cause. I tried clearing the Proton Data and it didn’t fix it. I have no clue whats causing it because the command didn’t change. It worked prior with the new fix

**Pull request merged**
